# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yext.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='yext.proto',
  package='yext',
  syntax='proto3',
  serialized_pb=_b('\n\nyext.proto\x12\x04yext\x1a google/protobuf/descriptor.proto:2\n\nschemapath\x12\x1d.google.protobuf.FieldOptions\x18\x90\x08 \x01(\t:5\n\tyang_name\x12!.google.protobuf.EnumValueOptions\x18\x90\x08 \x01(\tb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


SCHEMAPATH_FIELD_NUMBER = 1040
schemapath = _descriptor.FieldDescriptor(
  name='schemapath', full_name='yext.schemapath', index=0,
  number=1040, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=_b("").decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
YANG_NAME_FIELD_NUMBER = 1040
yang_name = _descriptor.FieldDescriptor(
  name='yang_name', full_name='yext.yang_name', index=1,
  number=1040, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=_b("").decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)

DESCRIPTOR.extensions_by_name['schemapath'] = schemapath
DESCRIPTOR.extensions_by_name['yang_name'] = yang_name

google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(schemapath)
google_dot_protobuf_dot_descriptor__pb2.EnumValueOptions.RegisterExtension(yang_name)

import grpc
from grpc.beta import implementations as beta_implementations
from grpc.beta import interfaces as beta_interfaces
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities
# @@protoc_insertion_point(module_scope)
